---
- name: Configure
  hosts: all
  gather_facts: F
  # 在远程用sudo执行
  sudo: yes
  # 或者这种方式
  remote_user: root
  tasks:
  - name: Copy /etc/hosts to other nodes
    copy: src=/etc/hosts dest=/etc/hosts mode=644
  - name: Copy /etc/hosts to other nodes
    # 或者这种方式
    remote_user: root
    copy: src=/etc/hosts dest=/etc/hosts mode=644